[package]
name = "rust_soong_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
light-rc-arena = "0.1.2"
serde = { version = "1.0", features = ["derive"] }
strum_macros = "0.27.2"
toml = "0.9.8"
